config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  devise_for :employers, :skip => [:registrations]
  as :employers do
    get 'employers/edit' => 'devise/registrations#edit', :as => 'edit_employer_registration'
    put 'employers' => 'devise/registrations#update', :as => 'employer_registration'
  end

  devise_for :admins, :skip => [:registrations]

  resources :jobs
  resources :job_applications, :except => [:new]

  resources :users, :except => :index
  resources :employers
  resources :admins

  get 'user/:id/job-applications' => 'users#job_applications', :as => 'user_applications'
  get 'job/:job_id/new-application' => 'job_applications#new', :as => 'new_job_application'
  get 'employer/:id/jobs' => 'employers#jobs', :as => 'employer_jobs'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_admin_dropdown.html.erb
<li><%= link_to "My Profile", current_admin %></li>
<li><%= link_to "Sign Out", destroy_admin_session_path, :method => :delete %></li>

app/views/home/_admin_home.html.erb
<div style="margin-top:50px">
  <%= link_to 'Manage Admins', admins_path , :class => "btn btn-default" %><br><br>
  <%= link_to 'Manage Employers', employers_path, :class => "btn btn-default"  %>
</div>

app/views/home/_employer_dropdown.html.erb
<li><%= link_to "My Profile", current_employer %></li>
<li><%= link_to "My Posted Jobs", employer_jobs_path(:id => current_employer.id) %></li>
<li><%= link_to "Sign Out", destroy_employer_session_path, :method => :delete %></li>

app/views/home/_employer_home.html.erb
<div style="margin-top:50px;">
  <% @jobs = current_employer.posted_jobs %>
  <%= render template: "employers/jobs.html.erb" %>
</div>

app/views/home/_user_dropdown.html.erb
<li><%= link_to "My Profile", current_user %></li>
<li><%= link_to "My Job Applications", user_applications_path(:id => current_user.id) %></li>
<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>

app/views/home/_user_home.html.erb
<div style="margin-top:50px;">
  <% @jobs = Job.where("deadline >= ?", Time.zone.now) %>
  <%= render template: "jobs/index.html.erb" %>
</div>

app/views/home/index.html.erb
<% if user_signed_in?%>
    <%= render 'user_home' %>
<% elsif admin_signed_in? %>
    <%= render 'admin_home' %>
<% elsif employer_signed_in? %>
    <%= render 'employer_home' %>
<% else %>
    <div style="margin-top:50px;">
      <% @jobs = Job.where("deadline >= ?", Time.zone.now) %>
      <%= render template: "jobs/index.html.erb" %>
    </div>    
<% end %>