config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  devise_for :employers, :skip => [:registrations]
  as :employers do
    get 'employers/edit' => 'devise/registrations#edit', :as => 'edit_employer_registration'
    put 'employers' => 'devise/registrations#update', :as => 'employer_registration'
  end

  devise_for :admins, :skip => [:registrations]

  resources :jobs
  resources :job_applications, :except => [:new]

  resources :users, :except => :index
  resources :employers
  resources :admins

  get 'user/:id/job-applications' => 'users#job_applications', :as => 'user_applications'
  get 'job/:job_id/new-application' => 'job_applications#new', :as => 'new_job_application'
  get 'employer/:id/jobs' => 'employers#jobs', :as => 'employer_jobs'

end

app/models/employer.rb
class Employer < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :timeoutable

  has_many :posted_jobs, :class_name => "::Job", :dependent => :destroy

  validates_presence_of :company_name, :contact_name
  validates :email, presence: true, uniqueness: true

  validates_presence_of :password, :on => :create
  validates_confirmation_of :password

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :create, :new, :destroy]
  before_action :authenticate_employer!, only: [:update, :edit, :show, :jobs]
  before_action :set_employer, only: [:show, :edit, :update, :destroy, :jobs]
  before_action :check_logged_in_employer, only: [:update, :edit, :show, :jobs]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        format.html { redirect_to employers_path, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        sign_out(current_employer)
        sign_in(@employer, :bypass => true)
        format.html { redirect_to @employer, notice: 'Profile successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def jobs
    @jobs = @employer.posted_jobs
  end

  private

    def check_logged_in_employer
      unless (current_employer == @employer)
        redirect_to root_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:company_name, :contact_name, :email, :password, :password_confirmation)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@employer) do |f| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% @employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-default"%>
  </div>
<% end %>

app/views/employers/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>

<%= form_for(@employer) do |f| %>
    <% if @employer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employer.errors.count, "error") %> prohibited the changes from being saved:</h2>

          <ul>
            <% @employer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :company_name %>
      <%= f.text_field :company_name, :required => true %>
    </div>
    <div class="field">
      <%= f.label :contact_name %>
      <%= f.text_field :contact_name, :required => true %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, :required => true %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
      <i>(leave blank if you don't want to change it)</i>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Update", :class => "btn btn-default"%>
    </div>
<% end %>

app/views/employers/index.html.erb
<div class="page-header">
    <h1>All Employers</h1>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Company name</th>
      <th>Contact name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.company_name %></td>
        <td><%= employer.contact_name %></td>
        <td><%= employer.email %></td>
        <td><%= link_to 'Remove', employer, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path, :class => "btn btn-default"%>

app/views/employers/jobs.html.erb
<div class="page-header">
  <h1>Posted Jobs</h1>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
    <th>Deadline</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, job, :class => "btn-link job-link" %></td>
        <td><%= job.description %></td>
        <td><%= job.category.name %></td>
        <td><%= job.deadline %></td>
        <td><%= link_to 'Edit', edit_job_path(job), :class => "btn btn-default" %>
          &nbsp&nbsp<%= link_to 'Delete', job, method: :delete, data: {confirm: "Are you sure?\nThis will also delete all the applications for this job."}, :class => "btn btn-danger" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path, :class => "btn btn-default" %>

<style>
    th, td {
        width: 50px;
    }
</style>

app/views/employers/new.html.erb
<div class="page-header">
  <h1>New employer</h1>
</div>

<%= form_for(@employer) do |f| %>
    <% if @employer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

          <ul>
            <% @employer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :company_name %>
      <%= f.text_field :company_name, :required => true %>
    </div>
    <div class="field">
      <%= f.label :contact_name %>
      <%= f.text_field :contact_name, :required => true %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, :required => true %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, :required => true %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :required => true %>
    </div>
    <div class="actions">
      <%= f.submit :class => "btn btn-default"%>
    </div>
<% end %>

app/views/employers/show.html.erb
<div class="page-header">
  <h1>Profile</h1>
</div>

<table class="table table-bordered">
  <tbody>
  <tr>
    <td>Company Name</td>
    <td><%= @employer.company_name %></td>
  </tr>
  <tr>
    <td>Contact Name</td>
    <td><%= @employer.contact_name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @employer.email %></td>
  </tr>
  </tbody>
</table>

<br>
<%= link_to 'Edit', edit_employer_path(@employer), :class=> "btn btn-default" %>